Add logging functionality
Adding logging functionality based on the code from suse-cloud-upgrade
Change rabbitmq password retrieve procedure

diff --git a/backup/backup-crowbar b/backup/backup-crowbar
--- a/backup/backup-crowbar
+++ b/backup/backup-crowbar
@@ -4,8 +4,10 @@
 # Backup and restore script for Crowbar
 #
 # 2013-2014, SUSE Linux Products GmbH
-# Authors: {bwiedemann,jdsn}@suse.de
+# Authors: {bwiedemann,jdsn,nkrinner}@suse.de
 #
+
+LOGFILE="/var/log/crowbar/backup-restore.log"
 
 CHEFFILES="etc/chef var/lib/couchdb/chef.couch var/lib/chef/cookbook_index"
 CROWBARFILES="etc/crowbar var/lib/crowbar"
@@ -19,13 +21,63 @@ for X in $EXCLUDEFILES ; do
   XFILES="--exclude $X $XFILES"
 done
 
+
+### Output / log handling
+# Based on the suse-cloud-upgrade scripts
+
+function prepare_log()
+{
+  mkdir -p "`dirname "$LOGFILE"`"
+
+  ### based on install-chef-suse.sh
+
+  # Copy stdout to fd 3
+  exec 3>&1
+  # Create fd 4 for logfile
+  exec 4>> "$LOGFILE"
+
+  # Set fd 1 and 2 to logfile
+  exec 1>&4 2>&1
+
+  # Send summary fd to original stdout
+  exec 6>&3
+}
+
+# send output only to logfile
+function echo_only_to_log () 
+{
+  echo -e "$(date '+%F %T %z'): $@" >&4
+}
+
+# send output to logfile and stdout
+function echo_and_log () 
+{
+  echo_only_to_log $@
+
+  echo -e $@ >&3
+}
+
+die() 
+{
+  # Send empty line & error to logfile
+  echo >&4
+  echo_and_log "Error: $@"
+ 
+  echo >&3
+  echo -e "Error: $@" >&3
+ 
+  exit 1
+}
+
+prepare_log
+
 function backup()
 {
   /etc/cron.daily/chef-couchdb-cleanup >/dev/null 2>&1 # to get smaller backups
   rccouchdb stop
 
   pushd / >/dev/null
-  echo "backing up to $FILE..."
+  echo_and_log "backing up to $FILE..."
   tar -czf "$FILE" $XFILES $BFILES
   popd >/dev/null
 
@@ -54,13 +106,13 @@ function purge()
   zypper -n rm `rpm -qa|grep -e crowbar -e chef -e rubygem -e susecloud` couchdb createrepo erlang rabbitmq-server sleshammer yum-common bind bind-chrootenv dhcp-server tftp
   rm -rf /opt/dell /var/log/{rabbitmq,nodes,crowbar,couchdb,chef,barclamps} /var/lib/{chef,couchdb,crowbar,dhcp,named,rabbitmq} /var/cache/chef /var/run/{chef,crowbar,named,rabbitmq} /var/chef /etc/sysconfig/{dhcpd,named,rabbitmq-server} /etc/{bind,chef,dhcp3,crowbar}
   killall epmd # need to kill again after uninstall
-  echo "you need to manually restore /etc/resolv.conf"
+  echo_and_log "you need to manually restore /etc/resolv.conf"
 }
 
 function restore_files()
 {
   pushd / >/dev/null
-  echo "restoring from $FILE..."
+  echo_and_log "restoring from $FILE..."
   tar -xf "$FILE"
   popd >/dev/null
 }
@@ -69,26 +121,16 @@ function check_resolv_conf
 {
   for ns in `grep "^\s*nameserver" /etc/resolv.conf | sed -e "s/\s*nameserver \([[:digit:]\.]\+\)[^[:digit:]\.]*/\1/" ` ; do
     if ! netcat -z $ns 53 ; then
-      echo "Error: Nameserver '$ns' is not available. Please reconfigure /etc/resolv.conf manually."
+      echo_and_log "Error: Nameserver '$ns' is not available. Please reconfigure /etc/resolv.conf manually."
       exit 1
     fi
     if ! ping -c1 turing.suse.de ; then
-      echo "Error: Nameserver '$ns' can not resolve or ping turing.suse.de. Please reconfigure /etc/resolv.conf manually"
+      echo_and_log "Error: Nameserver '$ns' can not resolve or ping turing.suse.de. Please reconfigure /etc/resolv.conf manually"
       exit 1
     fi
   done
 }
 
-function rabbitmq_get_password()
-{
-  RABBITPW=`grep --no-filename "^\s*amqp_pass" /etc/chef/{server,solr}.rb | sed -e "s/\s*amqp_pass \"\([^\"]\+\)\"/\1/" | sort | uniq`
-  if [ `printf "%s\n" $RABBITPW | wc -l` = 1 ] ; then
-    #rabbitmqctl change_password chef $RABBITPW
-    echo -n "$RABBITPW"
-  else
-    echo -n ""
-  fi
-}
 
 function reconfigure_rabbitmq()
 {
@@ -97,7 +139,14 @@ function reconfigure_rabbitmq()
   rabbitmqctl delete_user chef
 
   # get the original rabbitmq chef password
-  rabbit_chef_password=`rabbitmq_get_password`
+   RABBITPW=`grep --no-filename "^\s*amqp_pass" /etc/chef/{server,solr}.rb | sed -e "s/\s*amqp_pass \"\([^\"]\+\)\"/\1/" | sort | uniq`
+   if [ `printf "%s\n" $RABBITPW | wc -l` = 1 ] ; then
+     #rabbitmqctl change_password chef $RABBITPW
+     rabbit_chef_password=$RABBITPW
+   else
+     rabbit_chef_password=""
+   fi
+
   # if empty create a new one
   if [ -z "$rabbit_chef_password" ] ; then
     rabbit_chef_password=$( dd if=/dev/urandom count=1 bs=16 2>/dev/null | base64 | tr -d / )
@@ -115,7 +164,7 @@ function restore()
   check_resolv_conf
   zypper -n install -l -t pattern cloud_admin
   restore_files
-  echo -n "Waiting for install-suse-cloud to finish:"
+  echo_and_log  "Waiting for install-suse-cloud to finish:"
   # copied from qa_crowbarsetup
   screen -d -m -L /bin/bash -c "rm -f /tmp/chef-ready ; install-suse-cloud --verbose ; touch /tmp/chef-ready"
   sleep 2 # need to wait for initial deletion of chef-ready
@@ -123,10 +172,10 @@ function restore()
   while [ $n -gt 0 ] && [ ! -e /tmp/chef-ready ] ; do
     n=$(expr $n - 1)
     sleep 5;
-    echo -n .
+    echo_and_log .
   done
   if [ $n = 0 ] ; then
-    echo "timed out waiting for chef-ready"
+    echo_and_log "timed out waiting for chef-ready"
     exit 83
   fi
   rccouchdb stop
@@ -160,20 +209,20 @@ function restore()
 
   # check if crowbar is accessible
   if ! curl -m 59 -s --digest --user crowbar:crowbar localhost:3000 | grep -q /nodes/crowbar ; then
-    echo "Error: Could not connect to Crowbar."
-    echo "       Please see /var/log/crowbar/production.log for details."
+    echo_and_log "Error: Could not connect to Crowbar."
+    echo_and_log "       Please see /var/log/crowbar/production.log for details."
     exit 1
   fi
 }
 
 function help()
 {
-  echo "usage: $0 [help|backup|restore] <FILE>"
-  echo
-  echo " backup <FILE>"
-  echo "     create a backup tarball of admin node config data in <FILE>"
-  echo " restore <FILE>"
-  echo "     restore a backup of an admin node config from tarball <FILE>"
+  echo "usage: $0 [help|backup|restore] <FILE>" >&3
+  echo "" >&3
+  echo " backup <FILE>" >&3
+  echo "     create a backup tarball of admin node config data in <FILE>" >&3
+  echo " restore <FILE>" >&3
+  echo "     restore a backup of an admin node config from tarball <FILE>" >&3
 }
 
 FILE=${2:-/tmp/backup-crowbar.tar.gz}
