change echo/log handling, draft

diff --git a/backup/crowbar-backup b/backup/crowbar-backup
--- a/backup/crowbar-backup
+++ b/backup/crowbar-backup
@@ -35,6 +35,10 @@
 
 
 LOGFILE="/var/log/crowbar/backup-restore.log"
+exec > >(tee -a $LOGFILE)
+exec 2> >(tee -a $LOGFILE >&2 )
+
+
 if [ ! -d /var/log/crowbar/ ]; then
   mkdir /var/log/crowbar
 fi
@@ -63,8 +67,9 @@ FILEDEF=/tmp/backup-crowbar.tar.gz
 function restore_files()
 {
   # restore all or specific files from backup tarball
+  echo_with_timestamp "Restoring backup"
   pushd / >/dev/null
-  echo_and_log "Restoring from $FILE..."
+  echo "Restoring from $FILE..."
   tar -xf "$FILE" $@
   popd >/dev/null
 }
@@ -72,7 +77,7 @@ function restore_files()
 function extract_dns_forwarders()
 {
   # save the DNS forwarders in /etc/resolv.conf.forwarders
-  echo_and_log "Extracting DNS forwarders"
+  echo "Extracting DNS forwarders"
   [ -e /etc/bind/named.conf ] || return
   cp -a /etc/resolv.conf{,.forwarders}
   sed -i -e "/^\s*nameserver/d" /etc/resolv.conf.forwarders
@@ -84,7 +89,7 @@ function extract_dns_forwarders()
 function restore_dns_forwarders()
 {
   # restore the resolv.conf from backup resp. /etc/resolv.conf.forwarders
-  echo_and_log "Restoring DNS forwarders"
+  echo "Restoring DNS forwarders"
   if [ "$1" = "frombackup" -a ! -e /etc/resolv.conf.norestore ] ; then
     restore_files etc/resolv.conf.forwarders
   fi
@@ -94,14 +99,14 @@ function restore_dns_forwarders()
 function check_resolv_conf
 {
   # check if DNS servers are available and can resolve domain names
-  echo_and_log "Check if DNS is available and domain resolution works"
+  echo "Check if DNS is available and domain resolution works"
   for ns in `grep "^\s*nameserver" /etc/resolv.conf | sed -e "s/\s*nameserver \([[:digit:]\.]\+\)[^[:digit:]\.]*/\1/" ` ; do
     if ! netcat -zu $ns 53 ; then
-      echo_and_log "Error: Nameserver '$ns' is not available. Please reconfigure /etc/resolv.conf manually."
+      echo "Error: Nameserver '$ns' is not available. Please reconfigure /etc/resolv.conf manually."
       exit 1
     fi
     if ! getent hosts "$HOSTTEST" >/dev/null; then
-      echo_and_log "Error: Nameserver '$ns' can not resolve or ping $HOSTTEST. Please reconfigure /etc/resolv.conf manually"
+      echo "Error: Nameserver '$ns' can not resolve or ping $HOSTTEST. Please reconfigure /etc/resolv.conf manually"
       exit 1
     fi
   done
@@ -110,12 +115,13 @@ function check_resolv_conf
 function backup()
 {
   # create the backup tarball
+  echo_with_timestamp "Creating backup"
   /etc/cron.daily/chef-couchdb-cleanup >/dev/null 2>&1 # to get smaller backups
   extract_dns_forwarders
   rccouchdb stop
 
   pushd / >/dev/null
-  echo_and_log "Backing up to $FILE..."
+  echo "Backing up to $FILE..."
   tar -czf "$FILE" $XFILES $BFILES
   popd >/dev/null
 
@@ -127,7 +133,7 @@ function cleanup()
 {
   # stop crowbar related services and delete its config files
   # to be used on a deployed crowbar
-  echo_and_log "Cleaning up the system"
+  echo_with_timestamp "Cleaning up the system"
   extract_dns_forwarders
   restore_dns_forwarders
   pushd / >/dev/null
@@ -146,7 +152,7 @@ function cleanup()
 function purge()
 {
   # cleanup + uninstall all crowbar related packages
-  echo_and_log "Purging the system"
+  echo_with_timestamp "Purging the system"
   cleanup
   zypper -n rm `rpm -qa|grep -e crowbar -e chef -e rubygem -e susecloud` couchdb createrepo erlang rabbitmq-server sleshammer yum-common bind bind-chrootenv dhcp-server tftp
   rm -rf /opt/dell /var/log/{rabbitmq,nodes,crowbar,couchdb,chef,barclamps} /var/lib/{chef,couchdb,crowbar,dhcp,named,rabbitmq} /var/cache/chef /var/run/{chef,crowbar,named,rabbitmq} /var/chef /etc/sysconfig/{dhcpd,named,rabbitmq-server} /etc/{bind,chef,dhcp3,crowbar}
@@ -187,7 +193,8 @@ function reconfigure_rabbitmq()
 function restore()
 {
   # restore crowbar from tarball
-  echo_and_log "Restoring the system form the backup"
+  echo_with_timestamp "Restoring the system from backup"
+
 
   restore_dns_forwarders frombackup
   check_resolv_conf
@@ -197,7 +204,7 @@ function restore()
   restore_files
 
   # calling install-suse-cloud script
-  echo_and_log  "Waiting for install-suse-cloud to finish:"
+  echo  "Waiting for install-suse-cloud to finish:"
   # copied from qa_crowbarsetup
   screen -d -m -L /bin/bash -c "rm -f /tmp/chef-ready ; install-suse-cloud --verbose ; touch /tmp/chef-ready"
   sleep 2 # need to wait for initial deletion of chef-ready
@@ -208,7 +215,7 @@ function restore()
     echo -n .
   done
   if [ $n = 0 ] ; then
-    echo_and_log "Timed out waiting for chef-ready"
+    echo "Timed out waiting for chef-ready"
     exit 83
   fi
   echo
@@ -249,13 +256,13 @@ function restore()
 
   # check if crowbar is accessible
   if ! curl -m 59 -s --digest --user crowbar:crowbar localhost:3000 | grep -q /nodes/crowbar ; then
-    echo_and_log "Error: Could not connect to Crowbar."
-    echo_and_log "       Please see /var/log/crowbar/production.log for details."
+    echo "Error: Could not connect to Crowbar."
+    echo "       Please see /var/log/crowbar/production.log for details."
     exit 1
   fi
 }
 
-function echo_and_log()
+function echo_with_timestamp()
 {
   echo $@
   echo "$(date '+%F %T %z'): $@" >> $LOGFILE
